language: c

script: perl tid 3893

addons:
  apt:
    packages:
    - build-essential
    - perlbrew
    - cpanminus
    - libwww-perl
    - libxml-simple-perl
    - libxml-parser-perl
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
