#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Carp;

use Sys::Syslog qw(:DEFAULT setlogsock);
use Storable qw/nstore retrieve/;
use File::Find;
use File::Path;
use Encode 'encode';
use LWP::Simple qw/get/;
use XML::Simple; #sudo yum install  expat-devel perl-XML-Simple
use Data::Dumper;
setlogsock 'unix';
openlog($0, 'pid', 'local0');
my $regex = '\.(m2t|MP4|aac)$';
my $dept = '/record/';
my $nomakedir = 0;
my $tv = '/home/foltia/php/tv/';
my $tiddb = 'tid.db';
my %tidarc = ();
my $tid = \%tidarc;
#my %cat = qw#
#    1   アニメ
#    10  アニメ完了
#    7   OVA
#    5   アニメ関連
#    4   特撮
#    8   映画
#    3   テレビ
#    2   ラジオ
#    6   メモ
#    0   その他
##;
my %cat = qw#
    1   アニメ
    10  アニメ
    7   アニメ
    5   アニメ
    4   特撮
    8   アニメ
    3   アニメ
    2   ラジオ
    6   アニメ
    0   その他
#;

$tid->{0}->{title} = 'unknown';
$tid->{0}->{cat} = 0;
sub tid_to_name
{
  my $number = shift;
  my $title;
  my $cat;
  return unless($number); #number=0 => TIDの指定が不正です
  return if(exists($tid->{$number}));
  my $config = XMLin(get(sprintf 
    qq|http://cal.syoboi.jp/db.php?Command=TitleLookup&TID=%d|,
     $number));
	$title = $config->{TitleItems}->{TitleItem}->{Title};
	# リネームできんかった
	$title =~ s/\//／/g if($title);
	$title =~ s/\:/：/g if($title);
	$title =~ s/\*/＊/g if($title);
	$title =~ s/\?/？/g if($title);
	$title =~ s/\"/”/g if($title);
	$title =~ s/\</＜/g if($title);
	$title =~ s/\>/＞/g if($title);
	$title =~ s/\|/｜/g if($title);
	$title =~ s/\"/”/g if($title);
	$title =~ s/\!/！/g if($title); 
	$title =~ s/\\/＼/g if($title);
	$title =~ s/♡/_/g  if($title); 
	$tid->{$number}->{title} = $title;
	$tid->{$number}->{cat} = $config->{TitleItems}->{TitleItem}->{Cat};
	$tid->{$number}->{FirstYear} = $config->{TitleItems}->{TitleItem}->{FirstYear};
	$tid->{$number}->{FirstMonth} = $config->{TitleItems}->{TitleItem}->{FirstMonth};
	$tid->{$number}->{FirstEndYear} = $config->{TitleItems}->{TitleItem}->{FirstEndYear};
	$tid->{$number}->{FirstEndMonth} = $config->{TitleItems}->{TitleItem}->{FirstEndMonth};
	$tid->{$number}->{UserPoint} = $config->{TitleItems}->{TitleItem}->{UserPoint};
	$tid->{$number}->{UserPointRank} = $config->{TitleItems}->{TitleItem}->{UserPointRank};
	$tid->{$number}->{TitleYomi} = $config->{TitleItems}->{TitleItem}->{TitleYomi};
#syslog('info', "getting tid %d", $number);
	return;
}
sub main
{
	eval { $tid = retrieve($tiddb) if(-f $tiddb); };
	if($@) { unlink $tiddb; };

	foreach(@ARGV)
	{
		s/^(MAQ|MHD)\-//;
		next unless(/(\d+)/);
		my $number = $1;
		&tid_to_name($number);
		printf "%s\n", encode('utf-8', $tid->{$number}->{title});
	}	
	nstore $tid, $tiddb;
}
&main;

