#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Encode qw/encode decode/;
use Carp;
use DBI;
use DBD::Pg;
use DBD::SQLite;

# PostgreSQL
my $DSN="dbi:Pg:dbname=foltia;host=localhost;port=5432";
my $DBUser="foltia";
my $DBPass="foltiaadmin";

sub tid_to_name
{
  my $number = shift;
  my $title;
  my $cat;
  my $dbh;
$dbh = DBI->connect($DSN,$DBUser,$DBPass) || die $!;

  my $DBQuery =  <<"SQL";
  SELECT title
  FROM   foltia_program
  WHERE
    tid = ?
SQL

  my $sth = $dbh->prepare($DBQuery);
$sth->execute($number);
  ($title) = $sth->fetchrow_array;
  $sth->finish;
  $title = decode('utf-8', $title);
  $title =~ s/\//／/g if($title);
  $title =~ s/\:/：/g if($title);
  $title =~ s/\*/＊/g if($title);
  $title =~ s/\?/？/g if($title);
  $title =~ s/\"/”/g if($title);
  $title =~ s/\</＜/g if($title);
  $title =~ s/\>/＞/g if($title);
  $title =~ s/\|/｜/g if($title);
  $title =~ s/\"/”/g if($title);
  $title =~ s/\!/！/g if($title); 
  $title =~ s/\\/＼/g if($title);
  $title =~ s/♡/_/g  if($title); 
  $dbh->disconnect;
  return $title;
}

foreach (@ARGV)
{
printf "%s\n", encode('utf-8', &tid_to_name($_));
}
