#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Carp;
use DBI;
use DBD::Pg;
use Encode qw/encode decode/;

# PostgreSQL
our $DB_NAME = "foltia";
our $DB_USER = "foltia";
our $DB_PASS = "foltiaadmin";
our $DB_HOST = "127.0.0.1";
our $DB_PORT = "5432";


sub tid_to_name
{
  my $number = shift;
  my $title;
  my $cat;
  my $dbh = DBI->connect("dbi:Pg:dbname=$DB_NAME;host=$DB_HOST;port=$DB_PORT","$DB_USER","$DB_PASS") or die "$!\n Error: failed to connect to DB.\n";
  my $DBQuery =  <<"SQL";
  SELECT title
  FROM   foltia_program
  WHERE
    tid = $number
SQL
  my $sth = $dbh->prepare($DBQuery);
  $sth->execute();
  while (my $ary_ref = $sth->fetchrow_arrayref) {
  my ($row) = @$ary_ref;
  $title = decode('utf-8', $row);
  $title =~ s/\//／/g if($title);
  $title =~ s/\:/：/g if($title);
  $title =~ s/\*/＊/g if($title);
  $title =~ s/\?/？/g if($title);
  $title =~ s/\"/”/g if($title);
  $title =~ s/\</＜/g if($title);
  $title =~ s/\>/＞/g if($title);
  $title =~ s/\|/｜/g if($title);
  $title =~ s/\"/”/g if($title);
  $title =~ s/\!/！/g if($title); 
  $title =~ s/\\/＼/g if($title);
  $title =~ s/♡/_/g  if($title); 
    last;
  }
  $sth->finish;
  $dbh->disconnect;
  return $title;
}

foreach (@ARGV)
{
printf "%s\n", encode('utf-8', &tid_to_name($_));
}
